apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customer-profile
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=customer-profile"
    'backstage.io/kubernetes-namespace': dev
spec:
  type: service
  system: customer-service
  lifecycle: experimental
  owner: team1
  providesApis:
    - customer-profile
