apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: customer-profile
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: customer-profile
    apps.tanzu.vmware.com/has-tests: true
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: postgres-claim
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels 
      value:
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/language: java-dind
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/api-docs"
        owner: team1
        system: customer-service
        description: An example service
  source:
    git:
      ref:
        branch: main
      url: https://github.com/billglover/tanzu-wld-java-rest-app
    
